import env from "@configs/env";
import OpenAI from "openai";
import { buildSystemPrompt } from "../prompts/system.prompt";
import { ChatMessage } from "../types/chat.types";
import { ApplicationService } from "./application.service";

export class AiService extends ApplicationService {
  private client: OpenAI | null = null;
  private model: string;
  private static modelCooldowns = new Map<string, number>();

  constructor() {
    super();
    this.client = null; // Always reset on construction to pick up fresh env vars
    this.model = env.gemmaModel || "gemma-4-31b-it" || "gemma-4-26b-it";
  }

  private getClient(): OpenAI {
    if (!this.client) {
      const apiKey = env.gemmaApiKey;
      if (!apiKey) {
        throw new Error("GEMMA_API_KEY (or API_KEY) is not configured in your environment variables.");
      }
      this.client = new OpenAI({
        apiKey: apiKey,
        baseURL: env.gemmaBaseUrl || "https://api.gemma-ai.cn/v1/",
      });
    }
    return this.client;
  }

  private getFallbackModels(): string[] {
    const list: string[] = [];
    if (this.model) {
      list.push(this.model);
      if (!this.model.startsWith("models/")) {
        list.push(`models/${this.model}`);
      }
    }

    const backups = [
      "models/gemma-4-31b-it",
      "models/gemini-2.5-flash",
      "models/gemini-2.0-flash",
      "models/gemini-flash-latest",
      "models/gemini-2.0-flash-lite",
      "models/gemini-3.5-flash",
      "models/gemini-3.1-flash-lite",
    ];

    for (const backup of backups) {
      if (!list.includes(backup)) {
        list.push(backup);
      }
    }
    return list;
  }

  private isModelCoolingDown(modelName: string): boolean {
    const cooldownUntil = AiService.modelCooldowns.get(modelName);
    if (!cooldownUntil) return false;
    if (Date.now() > cooldownUntil) {
      AiService.modelCooldowns.delete(modelName);
      return false;
    }
    return true;
  }

  /**
   * Generates a chat response using the configured model, falling back to alternative models
   * if the current one is rate-limited or exhausted.
   * @param message The user's message
   * @param history The previous conversation history
   * @param dbContext Optional formatted DB context string to inject into system prompt
   * @returns The generated string response
   */
  async generateChatResponse(
    message: string,
    history: ChatMessage[] = [],
    dbContext?: string
  ): Promise<string> {
    // Build dynamic system prompt – inject live DB data when available
    const systemPromptContent = dbContext
      ? buildSystemPrompt(dbContext)
      : buildSystemPrompt("Hiện tại không thể tải dữ liệu nhà hàng. Vui lòng thử lại sau.");

    // Build the message array with System Prompt, History, and current User Message
    // Filter out any history items with missing/empty content (safety guard)
    const messages: OpenAI.Chat.ChatCompletionMessageParam[] = [
      {
        role: "system",
        content: systemPromptContent,
      },
      ...history
        .filter(msg => msg.content && typeof msg.content === "string" && msg.content.trim() !== "")
        .map(msg => ({
          role: msg.role,
          content: String(msg.content).trim(),
        })),
      {
        role: "user",
        content: message,
      },
    ];

    const fallbackModels = this.getFallbackModels();
    
    // Filter out models currently in cooldown
    let availableModels = fallbackModels.filter(m => !this.isModelCoolingDown(m));
    
    // If all candidate models are cooling down, ignore cooldown and retry all
    if (availableModels.length === 0) {
      console.warn("[AiService] All models are in cooldown. Resetting cooldowns to retry.");
      availableModels = fallbackModels;
    }

    let lastError: any = null;

    for (const modelToTry of availableModels) {
      try {
        console.log(`[AiService] Attempting to generate response with model: ${modelToTry}`);
        
        const response = await this.getClient().chat.completions.create({
          model: modelToTry,
          messages,
          temperature: 0.6,
          top_p: 0.9,
          max_tokens: 512,
        });

        const rawAnswer = response.choices[0]?.message?.content || "";

        // Strip <thought>...</thought> blocks if present
        const answer = rawAnswer
          .replace(/<thought>[\s\S]*?<\/thought>/g, "")
          .trim();

        if (!answer) {
          throw new Error(`Empty response generated by model ${modelToTry}`);
        }

        return answer;
      } catch (error: any) {
        console.error(`[AiService] Error generating response with model "${modelToTry}":`, error.message || error);
        
        // Put the failed model on cooldown for 60 seconds
        AiService.modelCooldowns.set(modelToTry, Date.now() + 60000);
        lastError = error;
      }
    }

    console.error("[AiService] All candidate AI models failed to generate a response.");
    throw lastError || new Error("All AI models failed to generate response.");
  }
}
