import OpenAI from "openai";
import env from "@configs/env";
import { ApplicationService } from "./application.service";
import { ChatMessage } from "../types/chat.types";
import { buildSystemPrompt } from "../prompts/system.prompt";

export class AiService extends ApplicationService {
  private client: OpenAI | null = null;
  private model: string;

  constructor() {
    super();
    this.client = null; // Always reset on construction to pick up fresh env vars
    this.model = env.gemmaModel || "gemma-4-31b-it";
  }

  private getClient(): OpenAI {
    if (!this.client) {
      const apiKey = env.gemmaApiKey;
      if (!apiKey) {
        throw new Error("GEMMA_API_KEY (or API_KEY) is not configured in your environment variables.");
      }
      this.client = new OpenAI({
        apiKey: apiKey,
        baseURL: env.gemmaBaseUrl || "https://api.gemma-ai.cn/v1/",
      });
    }
    return this.client;
  }

  /**
   * Generates a chat response using the Gemma model via OpenAI SDK.
   * @param message The user's message
   * @param history The previous conversation history
   * @param dbContext Optional formatted DB context string to inject into system prompt
   * @returns The generated string response
   */
  async generateChatResponse(
    message: string,
    history: ChatMessage[] = [],
    dbContext?: string
  ): Promise<string> {
    try {
      // Build dynamic system prompt – inject live DB data when available
      const systemPromptContent = dbContext
        ? buildSystemPrompt(dbContext)
        : buildSystemPrompt("Hiện tại không thể tải dữ liệu nhà hàng. Vui lòng thử lại sau.");

      // Build the message array with System Prompt, History, and current User Message
      // Filter out any history items with missing/empty content (safety guard)
      const messages: OpenAI.Chat.ChatCompletionMessageParam[] = [
        {
          role: "system",
          content: systemPromptContent,
        },
        ...history
          .filter(msg => msg.content && typeof msg.content === "string" && msg.content.trim() !== "")
          .map(msg => ({
            role: msg.role,
            content: String(msg.content).trim(),
          })),
        {
          role: "user",
          content: message,
        },
      ];

      const response = await this.getClient().chat.completions.create({
        model: this.model,
        messages,
        temperature: 0.6,
        top_p: 0.9,
        max_tokens: 512,
      });

      const rawAnswer = response.choices[0]?.message?.content || "";

      // Gemma 4 31B includes <thought>...</thought> blocks (internal reasoning).
      // Strip them before returning the clean answer to the frontend.
      const answer = rawAnswer
        .replace(/<thought>[\s\S]*?<\/thought>/g, "")
        .trim();

      if (!answer) {
        throw new Error("No response generated by the AI model");
      }

      return answer;
    } catch (error) {
      console.error("[AiService] Error generating chat response:", error);
      throw error; // Re-throw to be handled by the controller
    }
  }
}
